#2024 Constraints on OEntities and OActors should be displayed in
eclipse/capella pull request #2025
Opened 2021-01-11 12:24 UTC by claudiasima-ro

referencing elements inside the Semantic Browser view

2021-01-11 12:51 UTC, claudiasima-ro commented
This issue was fixed for OEntities.
For OActors, and also for Physical Components of type Deploy (Node or Behavior), the issue will be fixed in another story, as it requires more analysis.

2021-01-12 14:31 UTC, minhtutonthat requested changes

2021-01-12 14:31 UTC, minhtutonthat commented on core/plugins/org.polarsys.capella.core.semantic.queries/src/org/polarsys/capella/core/semantic/queries/basic/queries/ModelElementConstraints.java
> +      if (object instanceof Entity)
This is not the good fix. The original problem is rather on the creation of constraint. When you create a constraint and associate it to an Entity or an OA, it associates to the Entity/OA but not the part. That's why this query does not return anything. When you do the same thing but for a Logical Component for example, you'll see that the constraint is properly associated to the part and when you click on the Logical Component, you'll see the constraining elements.

2021-01-19 16:16 UTC, georgiana-ecobici approved these changes

2021-01-20 14:16 UTC, minhtutonthat approved these changes

2021-01-20 14:16 UTC, merged