#2101 Extend Interpreter View popup menu
eclipse/capella pull request #2102
Opened 2021-02-18 15:58 UTC by GlennPlou

Change-Id: I327db2f281bd5b7a63780bc1778429f28dc24283
Signed-off-by: Glenn Plouhinec <glenn.plouhinec@obeo.fr>

2021-02-18 16:05 UTC, GlennPlou commented
The new tools of this PR extend the Interpreter View and will be operational in the next release of Sirius 6.5.0 which will integrate Acceleo 3.8.

2021-02-19 09:07 UTC, pdulth requested changes

2021-02-19 09:07 UTC, pdulth commented on core/plugins/org.polarsys.capella.core.sirius.ui/src/org/polarsys/capella/core/sirius/ui/handlers/CopyTextHandler.java
> +        builder.append(((ModelElement) o).getFullLabel());
getLabel

2021-02-19 09:28 UTC, GlennPlou commented on core/plugins/org.polarsys.capella.core.sirius.ui/plugin.properties
> +command.copyAsText=Copy
Done.

2021-02-19 09:28 UTC, GlennPlou commented on core/plugins/org.polarsys.capella.core.sirius.ui/plugin.xml
> +         point="org.eclipse.ui.bindings">
Done.

2021-02-19 09:28 UTC, GlennPlou commented on core/plugins/org.polarsys.capella.core.sirius.ui/src/org/polarsys/capella/core/sirius/ui/handlers/CopyTextHandler.java
> +        builder.append(((ModelElement) o).getFullLabel());
Done.

2021-02-19 09:29 UTC, GlennPlou commented
The commit has been amended. Recommendations have been taken into account.

2021-02-23 08:03 UTC, pdulth approved these changes

2021-02-23 08:04 UTC, merged