#2024 Constraints changes - help, junits
eclipse/capella pull request #2104
Opened 2021-02-22 14:05 UTC by claudiasima-ro

Fixes #2024

2021-02-22 14:10 UTC, pdulth commented
Can you do a rebase, i have squash both previous commits to one.

2021-02-22 14:11 UTC, pdulth commented
I didn't understood why this commit couldn't have been merged in the previous PR though.

2021-02-23 08:02 UTC, pdulth requested changes

2021-02-23 09:37 UTC, claudiasima-ro commented on doc/plugins/org.polarsys.capella.validation.doc/html/Validation Rules/design/well-formedness/data/ValidationRules.mediawiki
> +| colspan="2"|For a property, type of the default (resp. null) value shall be Undefined (implicit typing) or the property�s datatype or a super type of the property�s datatype
Done

2021-02-23 09:51 UTC, georgiana-ecobici approved these changes

2021-02-23 11:07 UTC, pdulth approved these changes

2021-02-23 11:11 UTC, pdulth requested changes

2021-02-23 11:11 UTC, pdulth commented on tests/plugins/org.polarsys.capella.test.validation.rules.ju/src/org/polarsys/capella/test/validation/rules/ju/testcases/dwf_d/Rule_DWF_D_58.java
> +  public static final String ENUMERATION_LITERAL_1 = "8ffa834f-648f-46aa-9e7c-abe35dc0289d";
can you rename from enumeration_literal to constraints?

2021-02-23 11:11 UTC, pdulth commented on tests/plugins/org.polarsys.capella.test.validation.rules.ju/src/org/polarsys/capella/test/validation/rules/ju/testcases/dwf_d/Rule_DWF_D_58.java
> +    return DatavaluePackage.Literals.ENUMERATION_LITERAL;
Constraint no?

2021-02-23 11:11 UTC, pdulth commented on tests/plugins/org.polarsys.capella.test.validation.rules.ju/src/org/polarsys/capella/test/validation/rules/ju/testcases/dwf_d/Rule_DWF_D_59.java
> +  public static final String ENUMERATION_LITERAL_1 = "ac316f95-96e0-4072-ae67-41732f1842d1";
same here

2021-02-23 16:36 UTC, georgiana-ecobici approved these changes

2021-02-24 07:34 UTC, georgiana-ecobici approved these changes

2021-02-24 09:25 UTC, pdulth approved these changes

2021-02-24 09:26 UTC, merged