New constraints changes
eclipse/capella pull request #2126
Opened 2021-03-15 08:19 UTC by claudiasima-ro

Change-Id: I060d3285a5584edec28522244eb9a3e186c72543
Signed-off-by: claudiasima <claudia.sima@thalesgroup.com>

2021-03-15 15:40 UTC, georgiana-ecobici requested changes
Add issue number.

2021-03-15 15:40 UTC, georgiana-ecobici commented on core/plugins/org.polarsys.capella.core.data.core.ui.quickfix/src/org/polarsys/capella/core/data/core/ui/quickfix/resolver/ConstraintLocationRule_Generator.java
> +
Add image (process).

2021-03-15 15:41 UTC, georgiana-ecobici commented on core/plugins/org.polarsys.capella.core.data.core.validation/plugin.xml
>                 </description>
This rule ensures that ConstrainedElements "Value" to "value".

2021-03-15 15:41 UTC, georgiana-ecobici commented on doc/plugins/org.polarsys.capella.validation.doc/html/Validation Rules/design/well-formedness/data/ValidationRules.html
> +				<td colspan="2">In monopart mode, this rule ensures that ConstrainedElements Value is not Part/PartDeploymentLink. Exception for EAB diagrams.</td>
This rule ensures that ConstrainedElements "Value" to "value".

2021-03-15 15:42 UTC, georgiana-ecobici commented on doc/plugins/org.polarsys.capella.validation.doc/html/Validation Rules/design/well-formedness/data/ValidationRules.mediawiki
> +| colspan="2"|In monopart mode, this rule ensures that ConstrainedElements Value is not Part/PartDeploymentLink. Exception for EAB diagrams.
"value"

2021-03-15 15:43 UTC, georgiana-ecobici commented on core/plugins/org.polarsys.capella.core.data.core.ui.quickfix/src/org/polarsys/capella/core/data/core/ui/quickfix/resolver/ConstraintLocationRule_Generator.java
> +        label = "Move constraint under first value of ConstrainedElements";
Move constraint under "the" first value of ConstrainedElements.

2021-03-16 13:43 UTC, pdulth requested changes
Hi, 
the "ConstrainedElements value" is not really user focused.
otherwise seems ok

2021-03-16 13:43 UTC, pdulth commented on core/plugins/org.polarsys.capella.core.data.core.ui.quickfix/src/org/polarsys/capella/core/data/core/ui/quickfix/resolver/ConstraintLocationRule_Generator.java
> +        label = "Move constraint under the first value of ConstrainedElements";
the first contrained element

2021-03-16 13:43 UTC, pdulth commented on core/plugins/org.polarsys.capella.core.data.core.validation/plugin.xml
> +                  ConstrainedElements for {0} should not be {1}.
{0} should not constrain {1}

2021-03-16 13:43 UTC, pdulth commented on core/plugins/org.polarsys.capella.core.data.core.validation/plugin.xml
> +                  In monopart mode: This rule ensures that ConstrainedElements value is not Part/PartDeploymentLink.
that a constraint is not constraining a Part nor PartDeploymentLink

2021-03-16 13:43 UTC, pdulth commented on core/plugins/org.polarsys.capella.core.data.core.validation/plugin.xml
> +                  In monopart mode: This rule ensures that a constraint is not stored under and have ConstrainedElements values as a Part/PartDeploymentLink.
and is contraining a Part or a PartDeploymentLink

2021-03-16 13:43 UTC, pdulth commented on core/plugins/org.polarsys.capella.core.data.core.validation/plugin.xml
> +                  Exception : If first ConstraintElements value is container PartDeploymentlink or empty ConstraintElements value
If a constraint is not constraining any element or if its stored under and constraining only a PartDeploymentLink

2021-03-16 13:43 UTC, pdulth commented on doc/plugins/org.polarsys.capella.validation.doc/html/Validation Rules/design/well-formedness/data/ValidationRules.html
> +				<td colspan="2">In monopart mode, this rule ensures that ConstrainedElements value is not Part/PartDeploymentLink. Exception for EAB diagrams.</td>
that a constrain is not constraining a Part nor a PartDeploymentLink

2021-03-16 13:46 UTC, pdulth commented
Hmm, i see in story that it is expected.. 🤨 I guess its ok then

2021-03-22 10:59 UTC, georgiana-ecobici approved these changes

2021-03-22 11:12 UTC, pdulth approved these changes

2021-03-22 11:12 UTC, merged