#2135 Creation of Constraint link not possible for certain elements
eclipse/capella pull request #2136
Opened 2021-03-22 14:26 UTC by MalinaStefaniaStoicanescu

Change-Id: Icc4b547e9417f0005933d62e46e5357355280d0c
Signed-off-by: MalinaStefaniaStoicanescu <malina.stoicanescu@thalesgroup.com>

2021-03-29 11:22 UTC, georgiana-ecobici approved these changes

2021-03-29 15:02 UTC, georgiana-ecobici commented on tests/plugins/org.polarsys.capella.test.diagram.tools.ju/model/XABDiagrams/XABDiagrams.capella
>  <org.polarsys.capella.core.data.capellamodeller:Project xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI"
?

2021-03-29 15:29 UTC, georgiana-ecobici requested changes
Not working on ActorCapabilityGeneralization.

2021-03-30 05:51 UTC, georgiana-ecobici approved these changes

2021-03-30 07:17 UTC, pdulth approved these changes

2021-03-30 07:17 UTC, merged