#2151 Disable menus on empty selection
eclipse/capella pull request #2157
Opened 2021-04-01 08:13 UTC by georgiana-ecobici

Resolves #2151

- Migrate, Open, Open and Show in Diagram Editor
- Disable Validate action when it contains empty selection

Change-Id: I6c7d64dcb5702a173a5bb5f5ef89df7e12e7e237
Signed-off-by: Georgiana Ecobici <georgiana-elena.ecobici@thalesgroup.com>

2021-04-01 09:36 UTC, georgiana-ecobici commented on core/plugins/org.polarsys.capella.core.validation.ui/src/org/polarsys/capella/core/validation/ui/DynamicActionProvider.java
>      }
This change is for the case when an element was previously selected, but you click on empty space in SB (selection inside the validate action is empty).

![image](https://user-images.githubusercontent.com/60220371/113274814-c75fa680-92e6-11eb-85cf-d21a77eb6aae.png)

2021-04-01 09:42 UTC, pdulth requested changes
We will merge it for IT2,
The first fix makes the migration project displayed but disabled when we click on any other elements.

2021-04-01 09:42 UTC, pdulth commented on core/plugins/org.polarsys.capella.core.data.migration/plugin.xml
> +		               <iterate
![image](https://user-images.githubusercontent.com/34767327/113275483-21f50480-92df-11eb-8caf-9528b09c11d1.png)

2021-04-07 13:15 UTC, pdulth commented
When you use one reference for the 3 commands, when clicking on an element, the non enabled will remain visible.

![image](https://user-images.githubusercontent.com/34767327/113871891-a5b56200-97b3-11eb-9fb8-73490ecbdc57.png)

To have the same behavior than previous version, can you try to add 3 dedicated references, one per handler rather than one with the three handlers?
![image](https://user-images.githubusercontent.com/34767327/113871983-bb2a8c00-97b3-11eb-8c63-4d8d776e26cd.png)
![image](https://user-images.githubusercontent.com/34767327/113872198-f75dec80-97b3-11eb-9720-e23f55100ab9.png)

2021-04-07 16:11 UTC, pdulth commented on core/plugins/org.polarsys.capella.core.data.migration/src/org/polarsys/capella/core/data/migration/handlers/MigrationPropertyTester.java
> +      return new ProjectMigrationHandler().isValidSelection(Arrays.asList(receiver));
When we disable commands through "Window / Preferences / Capella / CommandConfigurability / Migration"
the handler on the command is replaced by another one by "PreferenceHandler.getInstance(command).activateHandler

If we use the "classical one" here, the command will be disabled and still visible even if we used a visibleWhen in the menu command.
In the new patchset, we retrieve the current command handler (classical one or PreferenceHelper disabling one) then look if it is enabled.

2021-04-09 09:55 UTC, pdulth approved these changes

2021-04-09 09:56 UTC, merged