#2259 Enable creation of ES/AS from AbstractCapabilities (OA level)
eclipse/capella pull request #2260
Opened 2021-11-09 13:23 UTC by MalinaStefaniaStoicanescu

Resolve #2259 
Change-Id: Icac99288be170503a5530e2c8788f506e089a2c4
Signed-off-by: MalinaStefaniaStoicanescu <malina.stoicanescu@thalesgroup.com>

2021-11-09 15:43 UTC, georgiana-ecobici commented on core/plugins/org.polarsys.capella.core.sirius.analysis/src/org/polarsys/capella/core/sirius/analysis/CapellaServices.java
>    }
Keep old signature.

2021-11-09 15:44 UTC, georgiana-ecobici requested changes
Keep old api in CapellaServices.

2021-11-09 15:52 UTC, MalinaStefaniaStoicanescu commented on core/plugins/org.polarsys.capella.core.sirius.analysis/src/org/polarsys/capella/core/sirius/analysis/CapellaServices.java
>    }
Done

2021-11-10 08:57 UTC, georgiana-ecobici approved these changes

2021-11-10 08:57 UTC, pdulth approved these changes

2021-11-10 09:00 UTC, merged