#2304 In Semantic Browser, add "Involved Activities" category for "Operational Capability"
eclipse/capella pull request #2308
Opened 2022-01-13 08:43 UTC by nlepine

2022-01-14 10:21 UTC, pdulth requested changes

2022-01-14 10:21 UTC, pdulth commented on core/plugins/org.polarsys.capella.core.semantic.queries/plugin.xml
> +            name="Involving Capabilities">
Involving Operational Capabilities (ie like https://github.com/eclipse/capella/blob/71d049a46b03c4996bd1fa38fb1b074f8c1be4e3/core/plugins/org.polarsys.capella.core.semantic.queries/plugin.xml#L4445)

2022-01-14 10:21 UTC, pdulth commented on core/plugins/org.polarsys.capella.core.semantic.queries/plugin.xml
> +            name="Involved Activities">
Involving Operational Activities

2022-01-14 11:13 UTC, nlepine commented on core/plugins/org.polarsys.capella.core.semantic.queries/plugin.xml
> +            name="Involving Capabilities">
ok

2022-01-14 11:13 UTC, nlepine commented on core/plugins/org.polarsys.capella.core.semantic.queries/plugin.xml
> +            name="Involved Activities">
ok

2022-01-17 10:06 UTC, mPorhel requested changes
@nlepine please review the copyrights headers.

2022-01-17 10:06 UTC, mPorhel commented on core/plugins/org.polarsys.capella.core.semantic.queries/plugin.xml
> +  Copyright (c) 2018, 2022 THALES GLOBAL SERVICES.
Copyright (c) 2018, 2022 THALES GLOBAL SERVICES and others.

+ contributors - summary/scope of the change/ticket id

2022-01-17 10:06 UTC, mPorhel commented on core/plugins/org.polarsys.capella.core.semantic.queries/src/org/polarsys/capella/core/semantic/queries/basic/queries/OperationalActivityInvolvingCapabilities.java
> + * Copyright (c) 2022 THALES GLOBAL SERVICES.
Copyright (c) 2022 Obeo.

contributors - summary/scope of the change/ticket id

2022-01-17 10:06 UTC, mPorhel commented on tests/plugins/org.polarsys.capella.test.semantic.queries.ju/src/org/polarsys/capella/test/semantic/queries/ju/testcases/OperationalActivity_InvolvingCapabilities.java
> + * Copyright (c) 2022 THALES GLOBAL SERVICES.
Idem here, copyright must be changed before merge.

2022-01-17 10:06 UTC, mPorhel commented on tests/plugins/org.polarsys.capella.test.semantic.queries.ju/src/org/polarsys/capella/test/semantic/queries/ju/testcases/OperationalCapability_InvolvedActivities.java
> + * Copyright (c) 2022 THALES GLOBAL SERVICES.
Idem here, copyright must be changed before merge.

2022-01-17 10:06 UTC, mPorhel commented on tests/plugins/org.polarsys.capella.test.semantic.queries.ju/src/org/polarsys/capella/test/semantic/queries/ju/testsuites/SemanticQueriesTestSuite.java
> + * Copyright (c) 2018, 2022 THALES GLOBAL SERVICES.
Idem here, copyright must be changed before merge.

2022-02-01 13:44 UTC, pdulth commented
for me looks good. @mPorhel ?

2022-02-03 09:13 UTC, mPorhel commented
@pdulth Sounds good for me it suits Capella rules.

I would just have had the Signed-off-by: Nathalie Lépine <nathalie.lepine@obeo.fr>

2022-02-10 15:13 UTC, merged