Storyimage
eclipse/capella pull request #2394
Opened 2022-05-10 16:18 UTC by lfasani

2022-05-12 09:14 UTC, lfasani commented
Do not merge this PR because there is a bug in path conversion for image created from base64

2022-05-18 13:33 UTC, pdulth requested changes

2022-05-20 09:13 UTC, pdulth commented on tests/plugins/org.polarsys.capella.test.validation.rules.ju/src/org/polarsys/capella/test/validation/rules/ju/testcases/i/Rule_I_47_IncorrectImagePath.java
> +            "&lt;p>&lt;img src=&quot;file:/C:/Users/T0108576/Documents/Docs/Docs/11_Images/circle_ws2.png&quot; />&lt;/p>&#xA;");
I think you can override the diagnotician for this test by overriding the create diagnotician and use a CapellaDiagnostician
https://github.com/eclipse/capella/blob/master/tests/plugins/org.polarsys.capella.test.validation.rules.ju/src/org/polarsys/capella/test/validation/rules/ju/testcases/ValidationRuleTestCase.java#L151

something like 
new CapellaDiagnostician((TED)manager.getEditingDomain().getAdapterFactory(), new NullProgressMonitor());

2022-05-23 08:50 UTC, lfasani commented on tests/plugins/org.polarsys.capella.test.validation.rules.ju/src/org/polarsys/capella/test/validation/rules/ju/testcases/i/Rule_I_47_IncorrectImagePath.java
> +            "&lt;p>&lt;img src=&quot;file:/C:/Users/T0108576/Documents/Docs/Docs/11_Images/circle_ws2.png&quot; />&lt;/p>&#xA;");
Done

2022-05-24 08:34 UTC, pdulth approved these changes

2022-05-24 08:39 UTC, pdulth commented
I updated TOC

2022-05-30 13:31 UTC, merged