#2451 PP/OP/FC/Scenario Representation queries
eclipse/capella pull request #2473
Opened 2022-09-13 09:36 UTC by etraisnel2

Selecting a PP/OP/FC/Scenario Representation now also displays queries on their target element

Added cache in item provider in order not to compute queries multiple times

Change-Id: I6125506e61970826393466a9f62dd4ef0d86f109
Signed-off-by: Erwann Traisnel <erwann.traisnel@obeo.fr>

2022-09-13 09:38 UTC, etraisnel2 commented
JUnit tests to be realized yet , waiting for PR #2469 to be merged and use its test project

2022-09-14 13:30 UTC, pdulth requested changes

2022-09-14 13:30 UTC, pdulth commented on core/plugins/org.polarsys.capella.core.ui.semantic.browser.sirius/src/org/polarsys/capella/core/ui/semantic/browser/sirius/content/provider/SiriusSemanticBrowserContentProviderFactory.java
> +package org.polarsys.capella.core.ui.semantic.browser.sirius.content.provider;
header

2022-09-16 07:18 UTC, pdulth approved these changes

2022-09-16 11:47 UTC, merged