[#2490] Functional Exchange looping on the same function
eclipse/capella pull request #2491
Opened 2022-09-27 08:28 UTC by irina-toma

Resolves #2490

Change-Id: Idc8d7cfcd3e62c2508b17348642ddf08d6fe3fe4
Signed-off-by: Irina Toma <irina_toma@rocketmail.com>

2022-09-27 16:23 UTC, pdulth requested changes

2022-09-27 16:23 UTC, pdulth commented on core/plugins/org.polarsys.capella.core.data.fa.validation/plugin.xml
> +                               class="org.polarsys.capella.core.data.fa.validation.functionalExchange.FunctionalExchange_loopsOnSameFunction"
Can you also update the embedded documentation
https://github.com/eclipse/capella/tree/master/doc/plugins/org.polarsys.capella.validation.doc

2022-09-27 16:23 UTC, pdulth commented on core/plugins/org.polarsys.capella.core.data.fa.validation/src/org/polarsys/capella/core/data/fa/validation/functionalExchange/FunctionalExchange_loopsOnSameFunction.java
> +    // Raise a warning if one of exchange item convoyed by related functional exchanges are not convoyed by the port
comment not uptodate/to remove

2022-09-27 16:23 UTC, pdulth commented on core/plugins/org.polarsys.capella.core.data.fa.validation/plugin.xml
> +                               {0} (Functional Exchange) {1} loops on same {2} {3}.
on operational analysis, it's called an Interaction, can you adapt message accordingly

2022-09-27 16:23 UTC, pdulth commented on core/plugins/org.polarsys.capella.core.data.fa.validation/plugin.xml
> +                               This rule generates an error if the Functional Exchange has the source and target ports defined on the same Function.
can you adapt for operational analysis. there is no ports and function are called operational activity

2022-09-27 16:23 UTC, pdulth commented on core/plugins/org.polarsys.capella.core.data.fa.ui.quickfix/plugin.properties
> +quickFix.DCOM_23_Resolver_Delete.desc = Delete invalid Functional Exchange
Can you adapt message on Operational analysis level / Interaction

2022-09-27 16:23 UTC, pdulth commented on core/plugins/org.polarsys.capella.core.data.fa.ui.quickfix/src/org/polarsys/capella/core/data/fa/ui/quickfix/resolver/DCOM_23_Resolver_Source.java
> +  public void run(IMarker marker) {
The two "show" resolver doesn"t apply on Operational analsys layer. There is a AbstractCapellaMarkerResolution.canResolve that might allow to make it not visible on Interactions

2022-09-30 14:34 UTC, pdulth approved these changes

2022-09-30 14:36 UTC, pdulth requested changes
can you fix failing junit ?
https://ci.eclipse.org/capella/job/capella-product/job/PR-2491/4/testReport/junit/org.polarsys.capella.test.doc.ju/StyleCheckTestCase/StyleCheckTestCase/

To generate the documentation, you need to use the build.xml at the root folder of the plugin o keep the css.

2022-10-03 07:00 UTC, irina-toma commented on core/plugins/org.polarsys.capella.core.data.fa.ui.quickfix/plugin.properties
> +quickFix.DCOM_23_Resolver_Delete.desc = Delete
Michel told me to leave it like that :)

2022-10-03 07:02 UTC, irina-toma commented on core/plugins/org.polarsys.capella.core.data.fa.ui.quickfix/src/org/polarsys/capella/core/data/fa/ui/quickfix/resolver/DCOM_23_Resolver_Source.java
> +    final EObject modelElement = getModelElements(marker).get(0);
It doesn't, enabled() removes them from the list

2022-10-05 09:55 UTC, pdulth approved these changes

2022-10-05 09:55 UTC, merged