#2644 Add quick fix to remove image not found for diagram elements
eclipse/capella pull request #2645
Opened 2023-04-14 14:57 UTC by scosta-obeo

2023-04-19 13:58 UTC, lfasani requested changes

2023-04-19 13:58 UTC, lfasani commented on tests/plugins/org.polarsys.capella.test.validation.rules.ju/src/org/polarsys/capella/test/validation/rules/ju/testcases/i/Rule_I_46_IncorrectImagePath.java
> +        Optional<DNode> dNodeOpt = session.getOwnedViews().stream().flatMap(view -> {
display like this for more clarity
```
stream() //
    .filter(...) //
    .xxx(...) //
```

2023-04-19 13:58 UTC, lfasani commented on tests/plugins/org.polarsys.capella.test.validation.rules.ju/src/org/polarsys/capella/test/validation/rules/ju/testcases/i/Rule_I_46_IncorrectImagePath.java
> +    private static final String INVALID_DNODE = "_ecDJsCgEEeuc881X317kNw";
you could have updated `exchange-item-instance-and-part-model.aird` and `exchange-item-instance-and-part-model.capella` to add a OperationalCapability and an operational Entity and a [OCB] diagram to test both node with default image and other nodes

2023-04-19 13:58 UTC, lfasani commented on core/plugins/org.polarsys.capella.core.platform.sirius.sirius.validation/plugin.properties
> +quickFix.ImagePath_RemoveResolver.descDiagram = Remove missing image from diagram
Remove the missing image reference from the diagram

2023-06-07 16:16 UTC, lfasani approved these changes

2023-06-21 15:14 UTC, pdulth approved these changes

2023-06-29 09:47 UTC, merged