#2705 log info from accelerator commands
eclipse/capella pull request #2706
Opened 2023-08-23 14:57 UTC by mchoubby

2023-08-25 07:30 UTC, irina-toma requested changes

2023-08-25 07:30 UTC, irina-toma commented on core/plugins/org.polarsys.capella.core.projection.exchanges/src/org/polarsys/capella/core/projection/exchanges/PhysicalLinksCreator.java
> +          + " already have a physical link or the kind is not suitable.");
small typo: already has

2023-08-25 07:30 UTC, irina-toma commented on core/plugins/org.polarsys.capella.core.projection.exchanges/src/org/polarsys/capella/core/projection/exchanges/PhysicalLinksCreator.java
> +            + exchangeInput.getLabel() + " and target " + exchangeOutput.getLabel());
"and the target"

2023-08-25 07:30 UTC, irina-toma commented on core/plugins/org.polarsys.capella.core.projection.exchanges/src/org/polarsys/capella/core/projection/exchanges/ComponentExchangesCreator.java
> +            + exchangeInput_p.getLabel() + " and target " + exchangeOutput_p.getLabel());
"and the target"

2023-08-25 09:03 UTC, irina-toma approved these changes

2023-08-29 08:17 UTC, pdulth requested changes

2023-08-29 08:17 UTC, pdulth commented on core/plugins/org.polarsys.capella.core.projection.exchanges/src/org/polarsys/capella/core/projection/exchanges/DefaultExchangesCreator.java
> +        "The Component exchange " + ce.getName() + " has been succefully created between the exchange input component "
Can you make information message navigable towards the elements 
(using EmbeddedMessage in the status like below: https://github.com/eclipse/capella/blob/5dfdd588f90ee4bac0cd803e47d3bf065be809e4/core/plugins/org.polarsys.capella.core.projection.interfaces/src/org/polarsys/capella/core/projection/interfaces/generateInterfaces/Rule_FunctionPort.java#L93

2023-08-29 08:17 UTC, pdulth commented on core/plugins/org.polarsys.capella.core.projection.exchanges/src/org/polarsys/capella/core/projection/exchanges/EntityExchangesCreator.java
> +    Status status = new Status(IStatus.INFO, Activator.PLUGIN_ID,
same here

2023-08-31 07:47 UTC, pdulth requested changes

2023-08-31 07:47 UTC, pdulth commented on core/plugins/org.polarsys.capella.core.projection.exchanges/src/org/polarsys/capella/core/projection/exchanges/ComponentExchangesCreator.java
> +    logger.error(eMessage);
Is it an error? or an info

2023-09-04 07:42 UTC, pdulth approved these changes

2023-09-04 07:43 UTC, merged