[561365] Richtext can lost the last modification when switching tab
eclipse/capella pull request #330
Opened 2020-08-24 07:06 UTC by minhtutonthat

The actual solution gives side-effects on Windows event (e.g. unexpected
double click event). This patch provides a way to block the display of
editor while it is still loading its content.

Bug: 561365
Change-Id: Ie4febe641226dd431502e9974b3b00b8459f8498
Signed-off-by: Tu Ton <minhtutonthat@gmail.com>

2020-08-24 07:07 UTC, minhtutonthat commented
To merge when https://github.com/eclipse/kitalpha/pull/62 will be merged and a new Kitalpha will be integrated in Capella.

2020-08-24 12:04 UTC, sandupostaru approved these changes

2020-08-25 08:41 UTC, pdulth commented
Can you create a new bugzilla ticket, the 561365 is for the 1.4.1 / 1.3.3.
Thanks

2020-08-25 08:51 UTC, pdulth requested changes
please change bugzilla ticket

2020-08-27 11:27 UTC, pdulth approved these changes

2020-08-27 11:28 UTC, merged