Master bug 566467
eclipse/capella pull request #343
Opened 2020-08-28 06:18 UTC by aliakar82

2020-08-28 06:57 UTC, pdulth requested changes
can you use formatOutput="true" in your build.xml to generate formatted htmls.
Thanks

https://github.com/eclipse/capella/blob/master/doc/plugins/org.polarsys.capella.ui.doc/build.xml#L38

2020-09-01 14:45 UTC, pdulth approved these changes

2020-09-01 19:34 UTC, pdulth submitted a review, later dismissed

2020-09-02 07:21 UTC, pdulth approved these changes

2020-09-02 13:41 UTC, sandupostaru commented on doc/plugins/org.polarsys.capella.th.doc/html/Interfaces and Data Modeling/Advanced Constructs.html
> +			<li>In the Variant, one value of the discriminant can be associated to any number (0 or more) of properties. By convention a variant property that has no discriminant value associated is deemed to
`??` typo?

2020-09-02 13:41 UTC, sandupostaru commented on doc/plugins/org.polarsys.capella.th.doc/html/Interfaces and Data Modeling/Interfaces and Data Modeling.html
> +<?xml version='1.0' encoding='utf-8' ?><!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
Was this file not generated ?

2020-09-02 13:44 UTC, pdulth commented on doc/plugins/org.polarsys.capella.th.doc/html/Interfaces and Data Modeling/Interfaces and Data Modeling.html
> +<?xml version='1.0' encoding='utf-8' ?><!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
idk

2020-09-02 13:44 UTC, pdulth commented on doc/plugins/org.polarsys.capella.th.doc/html/Interfaces and Data Modeling/Advanced Constructs.html
> +			<li>In the Variant, one value of the discriminant can be associated to any number (0 or more) of properties. By convention a variant property that has no discriminant value associated is deemed to
indeed

2020-09-02 13:55 UTC, sandupostaru approved these changes

2020-09-02 14:11 UTC, merged