[567246] Add a warning message in the DeleteCapellaElement dialog box
eclipse/capella pull request #373
Opened 2020-09-23 07:52 UTC by lfasani

This message is displayed when a representation is about to be deleted.

Change-Id: Ib5dd66e0e145d40a4737999c697fc778b2062a44
Signed-off-by: Laurent Fasani <laurent.fasani@obeo.fr>

2020-09-23 16:10 UTC, lfasani commented
-2 because I have to amend this commit to enhance a little the warning message

2020-09-28 09:12 UTC, lfasani commented
> -2 because I have to amend this commit to enhance a little the warning message

The code has been updated. It is ready to be reviewed.

2020-09-29 09:47 UTC, pdulth requested changes
Message of this dialog is customized by the status returned by CapellaDeleteCommand.preDeleteChecks(). 
https://github.com/eclipse/capella/blob/6ef8e899f3503c655a1c528a2d33442dc722e90d/core/plugins/org.polarsys.capella.core.platform.sirius.ui.actions/src/org/polarsys/capella/core/platform/sirius/ui/commands/CapellaDeleteCommand.java#L142-L150

Can you add your warning representation check after the other error message.
In this preCheck method you will have access to getAllElementsToDelete() which will contains the representations instead of _referencingElements

To display a warning instead of an error:
https://github.com/eclipse/capella/blob/6ef8e899f3503c655a1c528a2d33442dc722e90d/core/plugins/org.polarsys.capella.core.ui.toolkit/src/org/polarsys/capella/core/ui/toolkit/dialogs/ConfirmDeleteCapellaElementDialog.java#L286-L289

2020-10-02 16:42 UTC, lfasani commented
> 
> 
> Message of this dialog is customized by the status returned by CapellaDeleteCommand.preDeleteChecks().
> 
> https://github.com/eclipse/capella/blob/6ef8e899f3503c655a1c528a2d33442dc722e90d/core/plugins/org.polarsys.capella.core.platform.sirius.ui.actions/src/org/polarsys/capella/core/platform/sirius/ui/commands/CapellaDeleteCommand.java#L142-L150
> 
> Can you add your warning representation check after the other error message.
> In this preCheck method you will have access to getAllElementsToDelete() which will contains the representations instead of _referencingElements
> 
> To display a warning instead of an error:
> 
> https://github.com/eclipse/capella/blob/6ef8e899f3503c655a1c528a2d33442dc722e90d/core/plugins/org.polarsys.capella.core.ui.toolkit/src/org/polarsys/capella/core/ui/toolkit/dialogs/ConfirmDeleteCapellaElementDialog.java#L286-L289

comments have been taken into account

2020-10-06 08:47 UTC, pdulth requested changes

2020-10-06 08:47 UTC, pdulth commented on core/plugins/org.polarsys.capella.core.platform.sirius.ui.actions/src/org/polarsys/capella/core/platform/sirius/ui/commands/CapellaDeleteCommand.java
> +        protectedElements = new Status(status, CapellaActionsActivator.PLUGIN_ID, message);
can you rename to "prechecks" or something like that

2020-10-06 08:47 UTC, pdulth commented on core/plugins/org.polarsys.capella.core.platform.sirius.ui.actions/src/org/polarsys/capella/core/platform/sirius/ui/commands/CapellaDeleteCommand.java
> +      } else {
Can you move else outside the first IF

2020-10-12 14:42 UTC, pdulth commented on core/plugins/org.polarsys.capella.core.ui.toolkit/src/org/polarsys/capella/core/ui/toolkit/dialogs/ConfirmDeleteCapellaElementDialog.java
>      if (!status.isOK()) {
I think this shall occurs only on ERROR status.
(if you have a warning, does the OK shall be disabled?)

2020-10-14 13:28 UTC, pdulth approved these changes

2020-10-15 11:28 UTC, pdulth approved these changes

2020-10-15 11:30 UTC, merged