Master bugfix 567249
eclipse/capella pull request #379
Opened 2020-10-01 11:17 UTC by claudiasima-ro

Added icons and changed editor for traces

2020-10-01 11:28 UTC, georgiana-ecobici commented on core/plugins/org.polarsys.capella.core.platform.eclipse.ui.trace/plugin.properties
> +#
update header, change the last modification from 2015 to 2020.

Copyright (c) 2006, 2020 THALES GLOBAL SERVICES. ....

2020-10-01 11:29 UTC, georgiana-ecobici commented on core/plugins/org.polarsys.capella.core.platform.eclipse.ui.trace/src/org/polarsys/capella/core/platform/eclipse/capella/ui/trace/messages/messages.properties
> +# Copyright (c) 2006, 2018 THALES GLOBAL SERVICES.
unexpected changed lines, change only the line affected.

2020-10-01 11:30 UTC, georgiana-ecobici commented on core/plugins/org.polarsys.capella.core.platform.eclipse.ui.trace/src/org/polarsys/capella/core/platform/eclipse/capella/ui/trace/views/components/TraceTreeViewer.java
> +
remove extra space.

2020-10-01 11:30 UTC, georgiana-ecobici commented on core/plugins/org.polarsys.capella.core.platform.eclipse.ui.trace/src/org/polarsys/capella/core/platform/eclipse/capella/ui/trace/views/components/TraceTreeViewer.java
> +
delete this :)

2020-10-01 11:32 UTC, georgiana-ecobici commented on core/plugins/org.polarsys.capella.core.platform.sirius.ui.actions/META-INF/MANIFEST.MF
> +Manifest-Version: 1.0
only changed lines shall appear as changed.

2020-10-01 11:32 UTC, georgiana-ecobici commented on core/plugins/org.polarsys.capella.core.platform.sirius.ui.actions/plugin.xml
> -<!--
change only affected lines

2020-10-06 12:57 UTC, minhtutonthat requested changes

2020-10-06 12:57 UTC, minhtutonthat commented on core/plugins/org.polarsys.capella.core.platform.eclipse.ui.trace/plugin.xml
> +                definitionId="org.polarsys.capella.core.platform.sirius.ui.actions.TraceManager.expression">
Could you also move the expression to the plugin org.polarsys.capella.core.platform.eclipse.ui.trace?

2020-10-06 12:57 UTC, minhtutonthat commented on core/plugins/org.polarsys.capella.core.platform.eclipse.ui.trace/src/org/polarsys/capella/core/platform/eclipse/capella/ui/trace/views/components/TraceTreeViewer.java
> +import java.awt.Dimension;
Are all of these imports necessary?

2020-10-07 10:23 UTC, claudiasima-ro commented on core/plugins/org.polarsys.capella.core.platform.eclipse.ui.trace/META-INF/MANIFEST.MF
> +Import-Package: org.polarsys.capella.core.ui.properties.wizards
yes

2020-10-07 10:23 UTC, claudiasima-ro commented on core/plugins/org.polarsys.capella.core.platform.eclipse.ui.trace/src/org/polarsys/capella/core/platform/eclipse/capella/ui/trace/views/components/TraceTreeViewer.java
> +import java.awt.Dimension;
No, I removed them. Thanks!

2020-10-08 11:28 UTC, minhtutonthat approved these changes

2020-10-08 12:15 UTC, merged