567909
eclipse/capella pull request #419
Opened 2020-10-27 15:23 UTC by lfasani

The second  commit **[567909] Improve analysis selector to be more user friendly**  replaces the PR [405](https://github.com/eclipse/capella/pull/405)

2020-10-28 16:48 UTC, pdulth commented
Hi, 
I'm not sure this is the latest versions of  @SteveMonnier PR, 
for instance, https://github.com/eclipse/capella/pull/405#discussion_r508640447 it not included.

2020-10-29 12:48 UTC, lfasani commented
> 
> 
> Hi @lfasani
> I'm not sure this is the latest versions of @SteveMonnier PR,
> for instance, [#405 (comment)](https://github.com/eclipse/capella/pull/405#discussion_r508640447) it not included.

Done

2020-10-29 12:54 UTC, pdulth requested changes

2020-10-29 12:54 UTC, pdulth commented on core/plugins/org.polarsys.capella.core.sirius.ui/src/org/polarsys/capella/core/sirius/ui/actions/MoveRepresentationsAction.java
> +    List<DRepresentationDescriptor> validRepresentationDescriptors = getValidRepresentationDescriptors(selection);
descriptors shall also be from the same session, otherwise the run doesn't seems to work unlike MoveRepresentationMenuManager

2020-10-29 12:54 UTC, pdulth commented on core/plugins/org.polarsys.capella.core.platform.sirius.ui.navigator/src/org/polarsys/capella/core/platform/sirius/ui/navigator/actions/providers/RepresentationActionProvider.java
> -import org.polarsys.capella.core.platform.sirius.ui.navigator.actions.move.representation.MoveRepresentationMenuManager;
this class was also used in org.polarsys.capella.core.explorer.activity.ui\src\org\polarsys\capella\core\explorer\activity\ui\viewer\CapellaDiagramViewer
can you use your new class in it too.

2020-10-29 14:38 UTC, pdulth approved these changes

2020-10-29 15:27 UTC, merged