[568560] Validation Rule and QuickFix for incoherent Instance Role names
eclipse/capella pull request #429
Opened 2020-11-05 14:54 UTC by sandupostaru

2020-11-06 09:17 UTC, pdulth requested changes

2020-11-06 09:17 UTC, pdulth commented on core/plugins/org.polarsys.capella.core.data.interaction.validation/src/org/polarsys/capella/core/data/interaction/validation/scenario/InstanceRoleHasDifferentNameThanRepresentedInstance.java
> +        if (!StringUtil.isNullOrEmpty(representedInstanceName)) {
if the user set to empty the represented instance, then the validation rule will not raise an error

2020-11-06 09:19 UTC, pdulth commented on core/plugins/org.polarsys.capella.core.data.interaction.validation/src/org/polarsys/capella/core/data/interaction/validation/scenario/InstanceRoleHasDifferentNameThanRepresentedInstance.java
> +        if (!StringUtil.isNullOrEmpty(representedInstanceName)) {
Another validation rule will then be raised
![image](https://user-images.githubusercontent.com/34767327/98348859-8dc98e80-2019-11eb-9736-79e75fe477fc.png)

2020-11-09 12:52 UTC, pdulth requested changes
Can you update doc to add the added validation rule.
Thanks

2020-11-09 13:22 UTC, sandupostaru commented
> 
> 
> Can you update doc to add the added validation rule.
> Thanks

Done

2020-11-09 13:47 UTC, pdulth approved these changes

2020-11-09 13:47 UTC, merged